version: '3'
services:
  django:
    build:
      context: ./app
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - 8000
    env_file: .env
    depends_on:
      - postgres

  postgres:
    image: 'postgres:latest'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: db.env

  nginx:
    restart: always
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - '80:80'
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume:
